//! Cross-language golden tests using imported fixtures.
//!
//! These tests consume the imported fixtures in place; they do not edit or
//! duplicate them. Expected digests are pinned from the fixtures, not
//! generated by the Rust implementation under test.

use dolly_canonical_json::{ParseLimits, canonicalize, parse_core_json};
use std::path::PathBuf;

fn spec_dir() -> PathBuf {
    PathBuf::from("../../dolly-spec")
}

fn read_fixture(rel: &str) -> Vec<u8> {
    std::fs::read(spec_dir().join(rel))
        .unwrap_or_else(|e| panic!("failed to read fixture {rel}: {e}"))
}

// ---------------------------------------------------------------------------
// TST-CONFIG-003: effective config overlay
// ---------------------------------------------------------------------------

#[test]
fn tst_config_003_canonical_bytes_and_digest() {
    // The test verifies canonical bytes for {"cache":{"module":true},"inherited":1,"nullable":null,"tags":["module"]}
    let test_value = parse_core_json(
        br#"{"cache":{"module":true},"inherited":1,"nullable":null,"tags":["module"]}"#,
        ParseLimits::protocol_wire(),
    )
    .unwrap();
    let (bytes, digest) = canonicalize(&test_value).unwrap();

    // Verify canonical bytes
    let canonical_str = String::from_utf8(bytes.into_vec()).unwrap();
    assert_eq!(
        canonical_str,
        r#"{"cache":{"module":true},"inherited":1,"nullable":null,"tags":["module"]}"#
    );

    // Verify digest
    assert_eq!(
        digest.to_canonical_string(),
        "sha256:75d72a950e3a0e5a7ad5150b6a52bfc4f2bc83c001c23dd7d44045b13149d223"
    );
}

// ---------------------------------------------------------------------------
// TST-CORE-016: frozen effective config generation
// ---------------------------------------------------------------------------

#[test]
fn tst_core_016_legacy_digest() {
    let test_value = parse_core_json(
        br#"{"mode":"legacy","threshold":7}"#,
        ParseLimits::protocol_wire(),
    )
    .unwrap();
    let (_bytes, digest) = canonicalize(&test_value).unwrap();
    assert_eq!(
        digest.to_canonical_string(),
        "sha256:0406c7d60dad47428a106f950b07195c98317e0e3c3c3325b2ff2a77b44b7613"
    );
}

#[test]
fn tst_core_016_current_digest() {
    let test_value = parse_core_json(
        br#"{"mode":"current","threshold":9}"#,
        ParseLimits::protocol_wire(),
    )
    .unwrap();
    let (_bytes, digest) = canonicalize(&test_value).unwrap();
    assert_eq!(
        digest.to_canonical_string(),
        "sha256:f26d094f9ee954e3a5cc96e73cdac37fbd401b08a8efe888659b33cc53090778"
    );
}

// ---------------------------------------------------------------------------
// Empty object digest
// ---------------------------------------------------------------------------

#[test]
fn empty_object_digest() {
    let test_value = parse_core_json(b"{}", ParseLimits::protocol_wire()).unwrap();
    let (bytes, digest) = canonicalize(&test_value).unwrap();
    assert_eq!(bytes.as_bytes(), b"{}");
    assert_eq!(
        digest.to_canonical_string(),
        "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"
    );
}

// ---------------------------------------------------------------------------
// TST-CORE-009: activation ledger evidence digest
// ---------------------------------------------------------------------------

#[test]
fn tst_core_009_activation_ledger_evidence_digest() {
    let fixture_bytes =
        read_fixture("test-vectors/core/TST-CORE-009-activation-ledger-evidence.json");
    let fixture = parse_core_json(&fixture_bytes, ParseLimits::protocol_wire()).unwrap();

    // Navigate to stimulus.cases.complete.commands[1].record
    let obj = match &fixture {
        dolly_canonical_json::CanonicalJsonValue::Object(o) => o,
        _ => panic!("fixture should be an object"),
    };

    let stimulus = obj.get("stimulus").unwrap();
    let stimulus_obj = match stimulus {
        dolly_canonical_json::CanonicalJsonValue::Object(o) => o,
        _ => panic!("stimulus should be an object"),
    };

    let cases = stimulus_obj.get("cases").unwrap();
    let cases_obj = match cases {
        dolly_canonical_json::CanonicalJsonValue::Object(o) => o,
        _ => panic!("cases should be an object"),
    };

    let complete = cases_obj.get("complete").unwrap();
    let complete_obj = match complete {
        dolly_canonical_json::CanonicalJsonValue::Object(o) => o,
        _ => panic!("complete should be an object"),
    };

    let commands = complete_obj.get("commands").unwrap();
    let commands_arr = match commands {
        dolly_canonical_json::CanonicalJsonValue::Array(a) => a,
        _ => panic!("commands should be an array"),
    };

    // The second command (index 1) contains the record and expected_evidence_digest
    let cmd = &commands_arr[1];
    let cmd_obj = match cmd {
        dolly_canonical_json::CanonicalJsonValue::Object(o) => o,
        _ => panic!("command should be an object"),
    };

    let record = cmd_obj.get("record").unwrap();
    let expected_digest = match cmd_obj.get("expected_evidence_digest") {
        Some(dolly_canonical_json::CanonicalJsonValue::String(s)) => s.clone(),
        _ => panic!("expected_evidence_digest should be a string"),
    };

    // Compute the digest of the record
    let (_bytes, digest) = canonicalize(record).unwrap();
    assert_eq!(
        digest.to_canonical_string(),
        expected_digest,
        "activation ledger evidence digest mismatch"
    );
}

// ---------------------------------------------------------------------------
// protocol/examples/valid-module-activate.json: manifest_digest and effective_config_digest
// ---------------------------------------------------------------------------

#[test]
fn valid_module_activate_manifest_digest() {
    let fixture_bytes = read_fixture("protocol/examples/valid-module-activate.json");
    let fixture = parse_core_json(&fixture_bytes, ParseLimits::protocol_wire()).unwrap();

    let obj = match &fixture {
        dolly_canonical_json::CanonicalJsonValue::Object(o) => o,
        _ => panic!("fixture should be an object"),
    };

    let params = obj.get("params").unwrap();
    let params_obj = match params {
        dolly_canonical_json::CanonicalJsonValue::Object(o) => o,
        _ => panic!("params should be an object"),
    };

    let manifest = params_obj.get("manifest").unwrap();
    let manifest_obj = match manifest {
        dolly_canonical_json::CanonicalJsonValue::Object(o) => o,
        _ => panic!("manifest should be an object"),
    };

    // Get the declared manifest_digest
    let declared_digest = match manifest_obj.get("manifest_digest") {
        Some(dolly_canonical_json::CanonicalJsonValue::String(s)) => s.clone(),
        _ => panic!("manifest_digest should be a string"),
    };

    // Compute the digest of the manifest with manifest_digest omitted:
    // rebuild the object without manifest_digest.
    let mut members: Vec<(String, dolly_canonical_json::CanonicalJsonValue)> = Vec::new();
    for (key, value) in manifest_obj.iter() {
        if key != "manifest_digest" {
            members.push((key.to_string(), value.clone()));
        }
    }
    let manifest_without_digest_obj =
        dolly_canonical_json::CanonicalJsonObject::try_from_iter(members).unwrap();
    let manifest_without_digest_value =
        dolly_canonical_json::CanonicalJsonValue::Object(manifest_without_digest_obj);

    let (_bytes, digest) = canonicalize(&manifest_without_digest_value).unwrap();
    assert_eq!(
        digest.to_canonical_string(),
        declared_digest,
        "manifest_digest mismatch"
    );
}

#[test]
fn valid_module_activate_effective_config_digest() {
    let fixture_bytes = read_fixture("protocol/examples/valid-module-activate.json");
    let fixture = parse_core_json(&fixture_bytes, ParseLimits::protocol_wire()).unwrap();

    let obj = match &fixture {
        dolly_canonical_json::CanonicalJsonValue::Object(o) => o,
        _ => panic!("fixture should be an object"),
    };

    let params = obj.get("params").unwrap();
    let params_obj = match params {
        dolly_canonical_json::CanonicalJsonValue::Object(o) => o,
        _ => panic!("params should be an object"),
    };

    let manifest = params_obj.get("manifest").unwrap();
    let manifest_obj = match manifest {
        dolly_canonical_json::CanonicalJsonValue::Object(o) => o,
        _ => panic!("manifest should be an object"),
    };

    // Get the declared effective_config_digest
    let declared_digest = match manifest_obj.get("effective_config_digest") {
        Some(dolly_canonical_json::CanonicalJsonValue::String(s)) => s.clone(),
        _ => panic!("effective_config_digest should be a string"),
    };

    // Get the effective_config value
    let effective_config = manifest_obj.get("effective_config").unwrap();

    // Compute the digest of the effective_config
    let (_bytes, digest) = canonicalize(effective_config).unwrap();
    assert_eq!(
        digest.to_canonical_string(),
        declared_digest,
        "effective_config_digest mismatch"
    );
}

// ---------------------------------------------------------------------------
// Catalog manifest digest: deterministic across runs
// ---------------------------------------------------------------------------

#[test]
fn catalog_manifest_digest_deterministic() {
    let catalog1 = dolly_schema::embedded_schema_catalog().unwrap();
    let catalog2 = dolly_schema::embedded_schema_catalog().unwrap();
    let d1 = catalog1.manifest_digest();
    let d2 = catalog2.manifest_digest();
    assert_eq!(
        d1.to_canonical_string(),
        d2.to_canonical_string(),
        "catalog manifest digest must be deterministic"
    );
}

// ---------------------------------------------------------------------------
// TST-CORE-016 fixture: verify declared effective_config_digest matches computed
// ---------------------------------------------------------------------------

#[test]
fn tst_core_016_fixture_effective_config_digest() {
    let fixture_bytes =
        read_fixture("test-vectors/core/TST-CORE-016-frozen-effective-config-generation.json");
    let fixture = parse_core_json(&fixture_bytes, ParseLimits::protocol_wire()).unwrap();

    let obj = match &fixture {
        dolly_canonical_json::CanonicalJsonValue::Object(o) => o,
        _ => panic!("fixture should be an object"),
    };

    // The fixture has initial.current_module_config with effective_config and
    // effective_config_digest. Verify the declared digest matches the computed
    // JCS digest of the effective_config value.
    let initial = obj
        .get("initial")
        .and_then(|v| match v {
            dolly_canonical_json::CanonicalJsonValue::Object(o) => Some(o),
            _ => None,
        })
        .expect("initial should be an object");

    let current_config = initial
        .get("current_module_config")
        .and_then(|v| match v {
            dolly_canonical_json::CanonicalJsonValue::Object(o) => Some(o),
            _ => None,
        })
        .expect("current_module_config should be an object");

    let effective_config = current_config
        .get("effective_config")
        .expect("effective_config should be present");
    let declared_digest = match current_config.get("effective_config_digest") {
        Some(dolly_canonical_json::CanonicalJsonValue::String(s)) => s.clone(),
        _ => panic!("effective_config_digest should be a string"),
    };

    let (_bytes, digest) = canonicalize(effective_config).unwrap();
    assert_eq!(
        digest.to_canonical_string(),
        declared_digest,
        "TST-CORE-016: effective_config_digest mismatch"
    );
    // The effective_config is {"mode":"current","threshold":9}
    assert_eq!(
        declared_digest,
        "sha256:f26d094f9ee954e3a5cc96e73cdac37fbd401b08a8efe888659b33cc53090778"
    );
}

// ---------------------------------------------------------------------------
// protocol/examples/invalid-duplicate-key.txt: fails as CORE_INVALID_JSON
// ---------------------------------------------------------------------------

#[test]
fn invalid_duplicate_key_fails_as_core_invalid_json() {
    let fixture_bytes = read_fixture("protocol/examples/invalid-duplicate-key.txt");
    let result = parse_core_json(&fixture_bytes, ParseLimits::protocol_wire());
    assert!(result.is_err(), "duplicate key should fail");
    let err = result.unwrap_err();
    assert_eq!(
        err.code,
        dolly_canonical_json::CanonicalErrorCode::CoreInvalidJson,
        "should fail as CORE_INVALID_JSON"
    );
}

// ---------------------------------------------------------------------------
// Nested root: valid depth-64 embedded JsonValue doesn't consume enclosing budget
// ---------------------------------------------------------------------------

#[test]
fn nested_root_independent_depth() {
    // A valid depth-64 embedded JsonValue should not consume the enclosing
    // semantic root's budget. But depth 65 in the embedded root fails.
    //
    // Since the semantic depth is checked on the complete tree, depth-64
    // embedded inside a depth-1 container has total depth 65, which exceeds 64.
    // The spec says the embedded root is checked independently from depth zero.
    // This means: the enclosing root sees the embedded value as a leaf (depth 1
    // for the container), and the embedded value is separately checked at depth 64.

    // For the wire parse, depth 65 is under the 96 limit, so it passes.
    let mut inner = String::new();
    for _ in 0..64 {
        inner.push('[');
    }
    inner.push('1');
    for _ in 0..64 {
        inner.push(']');
    }
    let outer = format!("{{\"embedded\":{inner}}}");

    // Wire parse accepts it (depth 65 < 96)
    let result = parse_core_json(outer.as_bytes(), ParseLimits::protocol_wire());
    assert!(result.is_ok(), "wire parse should accept depth 65");

    // Semantic parse with limit 64 rejects it because the outer container's
    // semantic depth is 65 (1 + 64).
    let result = parse_core_json(outer.as_bytes(), ParseLimits::semantic(64).unwrap());
    assert!(
        result.is_err(),
        "semantic depth 65 should be rejected under limit 64"
    );
}

#[test]
fn tst_auth_007_runtime_state_cross_language_golden() {
    let fixture = parse_core_json(
        &read_fixture("test-vectors/core/TST-AUTH-007-physical-v2-bridge.json"),
        ParseLimits::protocol_wire(),
    )
    .unwrap();
    let root = match fixture {
        dolly_canonical_json::CanonicalJsonValue::Object(object) => object,
        _ => panic!("authority bridge vector must be an object"),
    };
    let stimulus = match root.get("stimulus").unwrap() {
        dolly_canonical_json::CanonicalJsonValue::Object(object) => object,
        _ => panic!("authority bridge stimulus must be an object"),
    };
    let golden = match stimulus.get("cross_language_golden").unwrap() {
        dolly_canonical_json::CanonicalJsonValue::Object(object) => object,
        _ => panic!("authority bridge golden must be an object"),
    };
    let bytes = match golden.get("state_canonical_bytes_utf8").unwrap() {
        dolly_canonical_json::CanonicalJsonValue::String(value) => value.as_bytes(),
        _ => panic!("authority bridge canonical bytes must be a string"),
    };
    let expected_digest = match golden.get("state_digest").unwrap() {
        dolly_canonical_json::CanonicalJsonValue::String(value) => value,
        _ => panic!("authority bridge digest must be a string"),
    };
    let value = parse_core_json(bytes, ParseLimits::semantic(64).unwrap()).unwrap();
    let (canonical, digest) = canonicalize(&value).unwrap();
    assert_eq!(canonical.as_bytes(), bytes);
    assert_eq!(digest.to_canonical_string(), expected_digest.as_str());
}
